name: Node.js CI

on: [deployment, push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node .
      env:
          SPREADSHEET_SECRETKEY: ${{ secrets.SPREADSHEET_SECRETKEY }}

    - run: bash ./bin/commit.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EMAIL: thura.ucsy@gmail.com
        GITHUB_USERNAME: Thura Aung
        GITHUB_REFERENCE: ${{ secrets.GIT_LOCATION }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch